// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("LiveMarkdownPreview")]
[assembly: AssemblyDescriptionAttribute("A small tool that watches a selected markdown file for changes and displays them in real time.")]
[assembly: GuidAttribute("949c5de6-a78e-4479-82de-f385d96a9ca0")]
[assembly: AssemblyProductAttribute("LiveMarkdownPreview")]
[assembly: AssemblyVersionAttribute("0.5.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0";
    }
}
